# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
