# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census_tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='reply_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
